spring:
  h2:
    console:
      # Set false for production
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:testdb
    username: changeThis
    password: changeThis
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8181
jwt:
  secret: 7E5YbJQVfA8nX9cxRpM4LdHgwK6DkZioLTru2P0hNtSsmW1UzvOGCqIe3lKFj # Change this in production !
kryptonite:
  user: root
  password: Kryptonite321!